version: 2
jobs:
  core_unit_test:
    docker:
      # Node 8 LTS
      - image: circleci/node:carbon
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
      - run: npm run test

  server_integration_test:
    docker:
      # Node 8 LTS
      - image: circleci/node:carbon
      # configuration database
      - image: circleci/postgres:9.6.2-alpine
        name: config_postgres
        environment:
            POSTGRES_USER: postgresql
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: aerogear_data_sync_db
      # memeolist database
      - image: circleci/postgres:9.6.2-alpine
        name: memeolist_postgres
        environment:
            POSTGRES_USER: postgresql
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: memeolist_db
      # keycloak
      - image: jboss/keycloak:3.4.3.Final
        name: keycloak_instance
        environment:
            KEYCLOAK_USER: admin
            KEYCLOAK_PASSWORD: admin
            DB_VENDOR: h2
    steps:
      - checkout
      - run:
          name: Wait for configuration database to start up
          command: dockerize -wait tcp://config_postgres:5432 -timeout 120s
      - run:
          name: Wait for memeolist database to start up
          command: dockerize -wait tcp://memeolist_postgres:5432 -timeout 120s
      - run:
          name: Wait for keycloak instance to start up
          command: dockerize -wait tcp://keycloak_instance:8080 -timeout 120s
      - run: REPO_NAME=data-sync-server ./scripts/clone_and_link.sh
      - run:
          command: cd data-sync-repos/data-sync-server && npm run db:init
          environment:
            POSTGRES_HOST: 'config_postgres'
            POSTGRES_PORT: '5432'
      - run:
          command: cd data-sync-repos/data-sync-server && npm run test:integration
          environment:
            POSTGRES_HOST: 'config_postgres'
            POSTGRES_PORT: '5432'
            MEMEOLIST_DB_HOST: 'memeolist_postgres'
            MEMEOLIST_DB_PORT: '5432'
            KEYCLOAK_HOST: 'keycloak_instance'
            KEYCLOAK_PORT: '8080'
  
  frontend_test:
    docker:
      # Node 8 LTS
      - image: circleci/node:carbon
    steps:
      - checkout
      - run: npm install
      - run: REPO_NAME=data-sync-ui ./scripts/clone_and_link.sh
      - run: cd data-sync-repos/data-sync-ui && npm run test
      - run: cd data-sync-repos/data-sync-ui && npm run build

workflows:
  version: 2
  build_and_push:
    jobs:
      - core_unit_test:
          filters:
            tags:
              only: /.*/
      - server_integration_test:
          filters:
            tags:
              only: /.*/
      - frontend_test:
          filters:
            tags:
              only: /.*/
